---
output: html_document
---

```{r}
# Load Palette
load(file = "C:/Users/skyep/Documents/Research/Plot_Animations/spalette.RData")
```

# Prelim Functions

```{r prelim}

# --- Rectangle --- #
rekt <- function(col = skrown$smoke, log = ""){
  if(log == ""){
      rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = col)
  } else if(log == "x"){
      rect(10^par("usr")[1], par("usr")[3], 10^par("usr")[2], par("usr")[4], col = col)
  } else if(log == "y"){
      rect(par("usr")[1], 10^par("usr")[3], par("usr")[2], 10^par("usr")[4], col = col)
  } else if (log == "xy"){
      rect(10^par("usr")[1], 10^par("usr")[3], 10^par("usr")[2], 10^par("usr")[4], col = col)
  }
}

# --- box around plot --- #
sox <- function(col = skrown$B2, log = ""){
    abline(col = col,
       v = if(log == "x" | log == "xy" | log == "yx") {10^c(par("usr")[1], par("usr")[2])} else {c(par("usr")[1], par("usr")[2])},
       h = if(log == "y" | log == "xy" | log == "yx") {10^c(par("usr")[3], par("usr")[4])} else {c(par("usr")[3], par("usr")[4])})}

# --- orientation lines --- #
skor <- function(x = 0, y = NULL, xlim = NULL, ylim = NULL, n1 = 11, n2 = 9, col = "white", log = ""){
  
  # loggers
  log.x <- (log == "x" | log == "xy"| log == "yx")
  log.y <- (log == "y" | log == "xy"| log == "yx")
  
  # vertical/horizontal markers 
  vlim <- if(is.null(xlim)){c(min(x), max(x))} else {c(xlim[1], xlim[2])}
  #if(log.x){vlim <- 10^vlim}
  
  hlim <- if(is.null(ylim)){ if(is.null(y)){c(min(x), max(x))} else {c(min(y), max(y,0))} } else {c(ylim[1], ylim[2])}
  #if(log.y){hlim <- 10^hlim}
  
  abline(v = seq(vlim[1], vlim[2], length.out=n1), col = col, lwd = 2)
  abline(h = seq(hlim[1], hlim[2], length.out=n2), col = col, lwd = 2)

  sox(log = log)
}

# --- Label Function --- # NORMALLY 1.7 is actually 1.5!!!!!!!!!!!!!!!!!!!
slab <- function(main = "", subb = "", xlab = "", ylab = "", col = skrown$B3){
  if(subb == ""){
            mtext(main, 3, 1,     font = 2, cex = 1.1, col = col)
    } else {mtext(main, 3, 1.75,  font = 2, cex = 1.1, col = col )}
  mtext(subb, 3, 0.28,           cex = 1   , col = col)
  mtext(xlab, 1, 2.75, font = 1, cex = 1.05, col = col)
  mtext(ylab, 2, 3   , font = 1, cex = 1.05, col = col)
}

```

# Splot: Skye-Plots

```{r}
# --- Skye-Plot function --- #
splot <- function(x, y = NULL,
                  col  = skrown$B2,
                  main = "", subb = "", xlab = NULL, ylab = NULL,
                  type = "p", pch = 19,
                  colr = skrown$smoke,
                  xlim = NULL, ylim = NULL,
                  skor = TRUE, n1 = 11, n2 = 9, skorcol = "white",
                  log  = "",
                  labs = 2, las = 1, coll = skrown$B3, ...){
  # frame
  plot(x, y, xlab = "", ylab = "", las = las,
       xlim = xlim, ylim = ylim, log = log, ...)
  
  # bg
  rekt(colr, log)

  # orient
  if(skor)(skor(x, y, xlim, ylim, n1, n2, skorcol, log = log))

  # add
  if(type == "p"){points(x, y, col = col, pch = pch, ...)
  } else {
    lines(x, y, col = col, type = type, ...)
  }

  # Labels
  slab(main, subb, col = coll)

  if(labs>0){
    if(!is.null(y)){
      xlabel <- if((substitute(x) != deparse1(x)) & labs > 1){paste(substitute(x), "=", deparse1(x))} else {substitute(x)}
      ylabel <- if((substitute(y) != deparse1(y)) & labs > 1){paste(substitute(y), "=", deparse1(y))} else {substitute(y)}
    } else {
      xlabel <- "Index"
      ylabel <- if((substitute(x) != deparse1(x)) & labs > 1){paste(substitute(x), "=", deparse1(x))} else {substitute(x)}
    }
    slab(xlab = xlabel, ylab = ylabel, col = coll)
  }
}
```

# SAVE

```{r}
save.image("splot.RData")
```

---

### Old buggy functions I don't really use anymore (but probably will have to revive soon)

```{r}
# # --- define inner function: pillarbox 
# rext <- function(N=1000,B=100, col = skrown$b1){rect(
#      xleft = c(par("usr")[[1]],N-ceiling(B/2)),
#      ybottom = c(par("usr")[[3]], par("usr")[[3]]),
#      xright = c(ceiling(B/2), par("usr")[[2]]),
#      ytop = c(par("usr")[[4]], par("usr")[[4]]),
#      col = col, border = NA)}
# 
# # --- within splot
# # requires B, N, bord, skol
# if(rexs){
#     rext(length(x),bord)
#     abline(v = c(ceiling(B/2),N-ceiling(B/2)), col = skol$green, lty = 2)
#     abline(v=c(par("usr")[1]),#par("usr")[3]),
#            h=par("usr")[4]) 
#   }


splot(x,y, log = "y")
abline(col = "red",
       v = if(log == "x" | log == "xy") {10^c(par("usr")[1], par("usr")[2])} else {c(par("usr")[1], par("usr")[2])},
       h = if(log == "y" | log == "xy") {10^c(par("usr")[3], par("usr")[4])} else {c(par("usr")[3], par("usr")[4])})


log <- "y"
```
